import pandas as pd

fc = pd.read_excel("outputs/Tahminlenen_Talep.xlsx")
pl = pd.read_excel("outputs/Arac_Planlama.xlsx", sheet_name="Arac Planlama")
oz = pd.read_excel("outputs/Arac_Planlama.xlsx", sheet_name="Ozet")

print("=== TAHMINLENEN_TALEP.XLSX ===")
print(f"Boyut       : {fc.shape}")
print(f"Sutunlar    : {fc.columns.tolist()}")
print(f"Tarih aralik: {fc['Tarih'].min().date()} - {fc['Tarih'].max().date()}")
print(f"Guzergah    : {fc[['Cikis TM','Varis TM']].drop_duplicates().shape[0]}")
print(f"NaN         : {fc.isnull().sum().sum()}")
print(f"Toplam desi : {fc['Tahmin Edilen Desi'].sum():,.0f}")
print()
print("Ilk 5 satir:")
print(fc.head(5).to_string(index=False))

print()
print("=== ARAC_PLANLAMA.XLSX — ANA SAYFA ===")
print(f"Boyut       : {pl.shape}")
print(f"Sutunlar    : {pl.columns.tolist()}")
print(f"Tarih aralik: {pl['Tarih'].min().date()} - {pl['Tarih'].max().date()}")
print(f"Arac tipleri: {sorted(pl['Arac Tipi'].unique())}")
print(f"NaN         : {pl.isnull().sum().sum()}")
print(f"Kiralik     : {pl[pl['Arac Tipi'].str.startswith('Kiralik')]['Maliyet'].sum():,.2f} TL")
print(f"Spot        : {pl[pl['Arac Tipi'].str.startswith('Spot')]['Maliyet'].sum():,.2f} TL")
print(f"TOPLAM      : {pl['Maliyet'].sum():,.2f} TL")
print()
print("Ilk 8 satir:")
print(pl.head(8).to_string(index=False))

print()
print("=== ARAC_PLANLAMA.XLSX — OZET SAYFASI ===")
print(oz.to_string(index=False))
